# Local access for the development PostgreSQL cluster.
local   all             all                                     trust
host    all             all             0.0.0.0/0               scram-sha-256
host    replication     postgres        172.21.0.0/16          scram-sha-256
