# airflow service routes

    location /airflow/ {
        proxy_pass http://airflow:8080/;
        proxy_redirect / /airflow/;
        proxy_set_header X-Forwarded-Prefix /airflow;
        proxy_set_header X-Script-Name /airflow;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
