# Camunda 7 service routes

location = /camunda7 {
    return 302 /camunda7/;
}

location /camunda7/ {
    set $upstream_camunda7 http://camunda7:8080;
    proxy_pass $upstream_camunda7;
    proxy_redirect ~^http://[^/]+(/.*)$ https://$host$1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Prefix /camunda7;
}
