# camunda service routes

    location = /camunda {
        return 302 /camunda/operate/;
    }

    location = /camunda/ {
        return 302 /camunda/operate/;
    }

    location /camunda/ {
        set $upstream_camunda http://camunda:8080;
        proxy_pass $upstream_camunda;
        proxy_redirect ~^http://[^/]+(/.*)$ https://$host$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /operate {
        return 302 /camunda/operate/;
    }

    location = /tasklist {
        return 302 /camunda/tasklist/;
    }

    location = /admin {
        return 302 /camunda/admin/setup;
    }

    location = /v2 {
        return 302 /camunda/v2/;
    }

    location /operate/ {
        return 302 /camunda$uri;
    }

    location /tasklist/ {
        return 302 /camunda$uri;
    }

    location /admin/ {
        return 302 /camunda$uri;
    }

    location /v2/ {
        return 302 /camunda$uri;
    }
