# favicon.ico service routes

    location = /favicon.ico {
        root /usr/share/nginx/html;
        try_files /favicon.ico =204;
        access_log off;
        log_not_found off;
    }

    location = /favicon.svg {
        alias /usr/share/nginx/html/favicon.svg;
        default_type image/svg+xml;
        access_log off;
        log_not_found off;
    }
