# gitea service routes

    location /gitea/ {
        proxy_pass http://gitea:3000/;
        proxy_redirect / /gitea/;
        proxy_cookie_path / /gitea/;
        proxy_set_header X-Forwarded-Prefix /gitea;
        proxy_set_header X-Script-Name /gitea;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
