# hive service routes

    location /hive/ {
        proxy_pass http://hive:10002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect / /hive/;
        proxy_set_header Accept-Encoding "";
        sub_filter_once off;
        sub_filter 'href="/' 'href="/hive/';
        sub_filter 'src="/' 'src="/hive/';
        sub_filter 'action="/' 'action="/hive/';
    }
