# jenkins service routes

    location ~ ^/jenkins/(toggleCollapse)$ {
        proxy_pass http://jenkins:8080/jenkins/$1;
        proxy_redirect / /jenkins/;
        include /etc/nginx/conf.d/proxy_params.inc;
    }

    location /jenkins/ {
        proxy_pass http://jenkins:8080;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Prefix /jenkins;
        proxy_set_header X-Script-Name /jenkins;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
