# jupyter service routes

    location /jupyter/ {
        proxy_pass http://jupyter:8888/;
        proxy_redirect / /jupyter/;
        proxy_set_header X-Forwarded-Prefix /jupyter;
        proxy_set_header X-Script-Name /jupyter;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
