# kafka-ui service routes

    location /kafka-ui/ {
        set $upstream_kafka_ui http://kafka-ui:8080;
        proxy_pass $upstream_kafka_ui;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
