# opensearch service routes

    location /opensearch/ {
        set $upstream_osd http://opensearch-dashboards:5601;
        proxy_pass $upstream_osd;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
