# sftpgo service routes

    location /sftpgo/ {
        proxy_pass http://sftpgo:8080/;
        proxy_redirect /web/ /sftpgo/web/;
        proxy_redirect / /sftpgo/;
        proxy_cookie_path /web/admin /sftpgo/web/admin;
        proxy_set_header X-Forwarded-Prefix /sftpgo;
        proxy_set_header X-Script-Name /sftpgo;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
