# spark service routes

    location /environment/ {
        proxy_pass http://spark:8080/environment/;
        include /etc/nginx/conf.d/proxy_params.inc;
    }

    location /logPage/ {
        proxy_pass http://spark:8080/logPage/;
        include /etc/nginx/conf.d/proxy_params.inc;
    }

    location /spark/ {
        proxy_pass http://spark:8080/;
        proxy_redirect ~^https?://[^/]+(/.*)$ $scheme://$host/spark$1;
        proxy_redirect / /spark/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /spark;
        proxy_set_header X-Script-Name /spark;
        proxy_set_header X-Spark-UI-Reverse-Proxy true;
    }
