# superset service routes

    location /superset/ {
        proxy_pass http://superset:8088/;
        proxy_redirect / /superset/;
        proxy_set_header X-Forwarded-Prefix /superset;
        proxy_set_header X-Script-Name /superset;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
