# uptime-kuma service routes

    location /uptime-kuma/ {
        proxy_pass http://uptime-kuma:3001/;
        proxy_redirect / /uptime-kuma/;
        proxy_set_header X-Forwarded-Prefix /uptime-kuma;
        proxy_set_header X-Script-Name /uptime-kuma;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
