# vault service routes

    location /vault/ {
        proxy_pass http://vault:8200/;
        proxy_redirect / /vault/;
        proxy_set_header X-Forwarded-Prefix /vault;
        proxy_set_header X-Script-Name /vault;
        include /etc/nginx/conf.d/proxy_params.inc;
    }
